name: Build KDU

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive 

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Auto-find and Build KDU
      shell: pwsh
      # Добавили /p:PlatformToolset=v143, чтобы проект "согласился" на сборку в стабильной версии VS2022
      run: |
        $slnFile = Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1
        if ($slnFile) {
            Write-Host "Отлично! Нашел файл проекта: $($slnFile.FullName)"
            msbuild $slnFile.FullName /m /p:Configuration=Release /p:Platform=x64 /p:SpectreMitigation=false /p:PlatformToolset=v143
        } else {
            Write-Error "Файл .sln не найден вообще нигде!"
            exit 1
        }

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KDU-Compiled
        path: '**\Release\*.exe'
